[build-system]
requires = ["setuptools>=75"]
build-backend = "setuptools.build_meta"

[project]
name = "one-shape-bo"
version = "0.1.0"
description = "Determine the best arrangement of perforations within a beam, to minimise compliance"
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "numpy>=2.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=8",
]

[tool.setuptools.packages.find]
where = ["src"]